### ISSUE TITLE
How do I run shotgun?

### ISSUE THREAD

**Issue by josegonzalez** [jack7890/Sinku#2]
Your readme says you include it, but neither the blog post nor readme say how its used, or what it is/does.

**Comment by zackkitzmiller** [comment]
If it doesn't have a 'trigger' method, it should.

**Comment by jack7890** [comment]
@josegonzalez It's a reloader.  Prevents you from having to manually restart the app to see changes reflected locally.  To run: `shotgun -I. index.rb`.
